steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/price-master-bh-202601060055/cloud-run-source-deploy/price-master-bih:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/price-master-bh-202601060055/cloud-run-source-deploy/price-master-bih:$COMMIT_SHA']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'price-master-bih'
      - '--image'
      - 'europe-west1-docker.pkg.dev/price-master-bh-202601060055/cloud-run-source-deploy/price-master-bih:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '10'
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - 'europe-west1-docker.pkg.dev/price-master-bh-202601060055/cloud-run-source-deploy/price-master-bih:$COMMIT_SHA'
